2021-01-04 16:35:29|INFO|gpload session started 2021-01-04 16:35:29
2021-01-04 16:35:29|INFO|setting schema 'public' for table 'texttable2'
2021-01-04 16:35:29|INFO|started gpfdist -p 8081 -P 8082 -f "pathto/data_file.txt" -t 30
2021-01-04 16:35:29|INFO|did not find an external table to reuse. creating ext_gpload_reusable_ccfc0c6e_4e67_11eb_bac2_00505698d059
2021-01-04 16:35:29|ERROR|invalid byte sequence for encoding "UTF8": 0xd6 0xd0  (seg0 slice1 10.152.8.113:7002 pid=21163)
CONTEXT:  External table ext_gpload_reusable_ccfc0c6e_4e67_11eb_bac2_00505698d059, line 1 of file gpfdist://*:pathto/data_file.txt
 encountered while running INSERT INTO public."texttable2" ("s1","s2") SELECT "s1","s2" FROM ext_gpload_reusable_ccfc0c6e_4e67_11eb_bac2_00505698d059
2021-01-04 16:35:29|INFO|rows Inserted          = 0
2021-01-04 16:35:29|INFO|rows Updated           = 0
2021-01-04 16:35:29|INFO|data formatting errors = 0
2021-01-04 16:35:29|INFO|gpload failed
