2020-12-17 15:38:22|INFO|gpload session started 2020-12-17 15:38:22
2020-12-17 15:38:22|INFO|setting schema 'public' for table 'texttable2'
2020-12-17 15:38:22|INFO|started gpfdist -p 8081 -P 8082 -f "pathto/data_file.txt" -t 30
2020-12-17 15:38:22|INFO|reusing external table ext_gpload_reusable_6f2dfb50_4035_11eb_b7f6_00505698d059
2020-12-17 15:38:22|ERROR|missing data for column "s2"  (seg0 slice1 10.152.8.113:7002 pid=6654)
CONTEXT:  External table ext_gpload_reusable_6f2dfb50_4035_11eb_b7f6_00505698d059, line 1 of gpfdist://*:pathto/data_file.txt: "123456789	abcd"
 encountered while running INSERT INTO public."texttable2" ("s1","s2") SELECT "s1","s2" FROM ext_gpload_reusable_6f2dfb50_4035_11eb_b7f6_00505698d059
2020-12-17 15:38:22|INFO|rows Inserted          = 0
2020-12-17 15:38:22|INFO|rows Updated           = 0
2020-12-17 15:38:22|INFO|data formatting errors = 0
2020-12-17 15:38:22|INFO|gpload failed
